version: "4.0"

networks:
  default:
    external: false

volumes:
  pgdata:
    driver: local

services:
  app:
    build:
      context: ../  # Path to Dockerfile relative to docker-compose file location
    volumes:
      - ./logs:/var/log/resonanz/
    ports:
      - "80:80"
    depends_on:
      - postgres

    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_ENGINE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/docker-entrypoint-initdb.d/pg_hba.conf
      - ./cp_pg_hba.sh:/docker-entrypoint-initdb.d/cp_pg_hba.sh

    expose:
      - "5432"
